helm:
  parameters:
  - name: knowledgeBaseServiceR2R.image.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/brain-r2r/r2r
    forcestring: true
  - name: knowledgeBaseServiceR2R.image.tag
    value: latest@sha256:972a8f969456e30f6d581faee64113b57312e7a82307bfb657d70b79961820c9
    forcestring: true
