apiVersion: v1
kind: Service
metadata:
  name: graph-clustering
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infomineo-chatbot.labels" . | nindent 4 }}
spec:
  selector:
    app: graph-clustering
  
  type: {{ .Values.services.knowledgeBaseServiceR2RGraphClustering.type }}
  ports:
    - port: {{ .Values.knowledgeBaseServiceR2RGraphClustering.service.port }}
      targetPort: {{ .Values.knowledgeBaseServiceR2RGraphClustering.service.targetPort }}
      protocol: TCP