apiVersion: v1
kind: Secret
metadata:
  name: r2r-env-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.knowledgeBaseServiceR2R.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}