apiVersion: v1
kind: Service
metadata:
  name: r2r
  namespace: {{ .Values.namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    {{- include "infomineo-chatbot.labels" . | nindent 4 }}
spec:
  selector:
    app: r2r
  
  ports:
    - protocol: TCP
      port: {{ .Values.services.knowledgeBaseServiceR2R.port }}
      targetPort: {{ .Values.services.knowledgeBaseServiceR2R.targetPort }}
  type: {{ .Values.services.knowledgeBaseServiceR2R.type }}
   