apiVersion: v1
kind: Service
metadata:
  name: r2r
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "infomineo-chatbot.labels" . | nindent 4 }}
spec:
  selector:
    app: r2r
  
  type: {{ .Values.services.knowledgeBaseServiceR2R.type }}
  ports:
    - port: {{ .Values.knowledgeBaseServiceR2R.service.port }}
      targetPort: {{ .Values.knowledgeBaseServiceR2R.service.targetPort }}
      protocol: TCP