name: Production - Build and Publish R2R Docker Image

on:
  push:
    branches: 
      - main
    paths:
      - 'js/**'
      - 'py/**'
      - 'services/**'

env:
  IMAGE_TAG : ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.PROD_GCP_PROJECT_ID }}/brain-r2r/r2r:latest
jobs:

  build-and-deploy:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Echo Commit Hash
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "Building commit hash: $COMMIT_HASH"

      - name: GCP Authenticate Github
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.PROD_GCP_SA_KEY }}'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker to GCP Artifact registry
        run: gcloud auth configure-docker "${{ secrets.GCP_REGION }}-docker.pkg.dev"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./py
          file: ./py/Dockerfile
          platforms: amd64
          no-cache: true
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
          provenance: false
          sbom: false